### ISSUE TITLE
Where are the scripts ??

### ISSUE THREAD

**Issue by delfuria** [dnnwerk/dnnScript#1]
Where are the SQL Scripts ??
I cannot reach to find they anymore.

**Comment by sleupold** [comment]
Which one are you looking for? Turbo Scripts are listed in "releases" section

**Comment by delfuria** [comment]
Thanks a lot for the reply, 
i visited this page
https://archive.codeplex.com/?p=dnnscript
but the link under the text
"Latest version should be available here" doesn't works.
Thanks for the right direction.

**Comment by sleupold** [comment]
I know, but unfortunately, I am unable to edit the content on CodePlex any longer.
