### ISSUE TITLE
Is TuroDNN still active/valid?

### ISSUE THREAD

**Issue by exweeto** [dnnwerk/dnnScript#16]
I have TurboDNN on a number of my older sites. I am in the process of upgrading these sites to the latest version of DNN (currently 9.10.2) and am using TurboUnSchemaXXX before upgrade, as normal. However, once upgraded to 9.10.2, I thought I should reapply the latest version of the TurboDNN script, but the latest that I can find appears to be for 9.3.2. Will this work with 9.10.2? If not, should I be removing TurboDNN completely from my sites? Is that even possible?

**Comment by sleupold** [comment]
yes, I am working on an update for DN 9.10, which should be available within the next few weeks, end of February or mid March as latest.

**Comment by exweeto** [comment]
Thanks Sebastian.
