### ISSUE TITLE
Question: Is it safe to use TurboDNN script w/o TurboSchema?

### ISSUE THREAD

**Issue by roman-yagodin** [dnnwerk/dnnScript#3]
I get a couple of issues with TurboSchema script on DNN 8.0.4 (see #4) - probably this is specific to the concrete DNN install. But is it safe to apply TurboDNN script only w/o TurboSchema one? Should I expect DNN or TurboDNN upgrade issues in the future?

**Comment by sleupold** [comment]
please see my reply to your other issue.
