### ISSUE TITLE
Error applying TurboDNN 0.9.9 Rev z4

### ISSUE THREAD

**Issue by roman-yagodin** [dnnwerk/dnnScript#5]
```
Message 1505, level 16, state 1, line 2
The CREATE UNIQUE INDEX statement was aborted because a duplicate key was found
for the object named "dbo.Roles" and an index named "IX_Roles_RoleGroup"
Duplicate key value: (<NULL>, Administrators).
The execution of this instruction has been interrupted.
```

**Comment by sleupold** [comment]
Yes, you are correct, it should be 
`CREATE UNIQUE NONCLUSTERED INDEX [IX_{objectQualifier}Roles_RoleGroup] ON {databaseOwner}[{objectQualifier}Roles]
    (RoleGroupID, PortalID, RoleName)
    INCLUDE (RoleId)
GO`
I'll fix it in the next version.

**Comment by sleupold** [comment]
fixed in Rev z5

**Comment by roman-yagodin** [comment]
0.9.9 Rev z5 applied without any issues, thanks!

**Comment by sleupold** [comment]
thanks for your feedback!
