### ISSUE TITLE
With DNN 9.2.0.

### ISSUE THREAD

**Issue by andre6622** [dnnwerk/dnnScript#7]
When running the script it ended up with these issues:

Msg 3729, Level 16, State 1, Line 632
Cannot DROP VIEW 'dbo.vw_ProfileBase' because it is being referenced by object 'UserProfileGranted'.
Msg 5074, Level 16, State 1, Line 636
The object 'vw_ProfileBase' is dependent on column 'PropertyKey'.
Msg 4922, Level 16, State 9, Line 636
ALTER TABLE DROP COLUMN PropertyKey failed because one or more objects access this column.
Msg 2714, Level 16, State 3, Procedure Sys_IsInteger, Line 2 [Batch Start Line 642]
There is already an object named 'Sys_IsInteger' in the database.
Msg 2714, Level 16, State 3, Procedure Sys_TryCastInteger, Line 2 [Batch Start Line 658]
There is already an object named 'Sys_TryCastInteger' in the database.
Msg 3729, Level 16, State 1, Line 697
Cannot DROP VIEW 'dbo.vw_UserRoles' because it is being referenced by object 'Journal_PermittedJournalIDs'.

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(162 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)
Msg 5074, Level 16, State 1, Line 1328
The object 'vw_RoleUsers' is dependent on column 'LowerEmail'.
Msg 4922, Level 16, State 9, Line 1328
ALTER TABLE DROP COLUMN LowerEmail failed because one or more objects access this column.

(0 rows affected)

(0 rows affected)

(0 rows affected)
Msg 5074, Level 16, State 1, Line 1418
The object 'vw_ProfileBase' is dependent on column 'PropertyKey'.
Msg 4922, Level 16, State 9, Line 1418
ALTER TABLE DROP COLUMN PropertyKey failed because one or more objects access this column.
Msg 2705, Level 16, State 5, Line 1422
Column names in each table must be unique. Column name 'PropertyKey' in table 'dbo.UserProfile' is specified more than once.

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(5 rows affected)
Msg 5074, Level 16, State 1, Line 1983
The object 'vw_ModuleTabs' is dependent on column 'Header'.
Msg 5074, Level 16, State 1, Line 1983
The object 'vw_ModulesOnTabs' is dependent on column 'Header'.
Msg 4922, Level 16, State 9, Line 1983
ALTER TABLE ALTER COLUMN Header failed because one or more objects access this column.
Msg 5074, Level 16, State 1, Line 1985
The object 'vw_ModuleTabs' is dependent on column 'Footer'.
Msg 5074, Level 16, State 1, Line 1985
The object 'vw_ModulesOnTabs' is dependent on column 'Footer'.
Msg 4922, Level 16, State 9, Line 1985
ALTER TABLE ALTER COLUMN Footer failed because one or more objects access this column.

(0 rows affected)
Msg 5074, Level 16, State 1, Line 2175
The object 'vw_Tabs' is dependent on column 'ModuleId'.
Msg 4922, Level 16, State 9, Line 2175
ALTER TABLE ALTER COLUMN ModuleId failed because one or more objects access this column.

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)
Msg 5074, Level 16, State 1, Line 2187
The object 'vw_Tabs' is dependent on column 'Indexed'.
Msg 5074, Level 16, State 1, Line 2187
The object 'vw_TabModules' is dependent on column 'Indexed'.
Msg 4922, Level 16, State 9, Line 2187
ALTER TABLE ALTER COLUMN Indexed failed because one or more objects access this column.

(0 rows affected)

(248 rows affected)

(0 rows affected)

(1 row affected)

(0 rows affected)

(425 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(6 rows affected)

(6 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(12 rows affected)

(0 rows affected)

(0 rows affected)

(80 rows affected)

(946 rows affected)

(0 rows affected)

(0 rows affected)

(12 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(1 row affected)

(19 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(525 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(5 rows affected)

(2000 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(2 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(3 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)

(0 rows affected)
Msg 3729, Level 16, State 1, Line 5156
Cannot DROP VIEW 'dbo.vw_Portals' because it is being referenced by object 'vw_PortalsDefaultLanguage'.
Msg 3729, Level 16, State 1, Line 5168
Cannot DROP FUNCTION 'dbo.FilePath' because it is being referenced by object 'vw_Portals'.
Msg 3729, Level 16, State 1, Line 5172
Cannot DROP VIEW 'dbo.vw_FilePaths' because it is being referenced by object 'FilePath'.
Msg 2714, Level 16, State 3, Procedure vw_FilePaths, Line 4 [Batch Start Line 5173]
There is already an object named 'vw_FilePaths' in the database.
Msg 2714, Level 16, State 3, Procedure FilePath, Line 3 [Batch Start Line 5186]
There is already an object named 'FilePath' in the database.
Msg 3729, Level 16, State 1, Line 5234
Cannot DROP FUNCTION 'dbo.HasChildTab' because it is being referenced by object 'vw_Tabs'.
Msg 3729, Level 16, State 1, Line 5239
Cannot DROP FUNCTION 'dbo.SuperuserTabID' because it is being referenced by object 'vw_Portals'.
Msg 2714, Level 16, State 3, Procedure SuperuserTabID, Line 3 [Batch Start Line 5240]
There is already an object named 'SuperuserTabID' in the database.
Msg 2714, Level 16, State 3, Procedure HasChildTab, Line 3 [Batch Start Line 5255]
There is already an object named 'HasChildTab' in the database.
Msg 3729, Level 16, State 1, Line 5438
Cannot DROP FUNCTION 'dbo.CoreMessaging_EmailFrequency' because it is being referenced by object 'vw_MessagesForDispatch'.
Msg 2714, Level 16, State 3, Procedure CoreMessaging_EmailFrequency, Line 1 [Batch Start Line 5439]
There is already an object named 'CoreMessaging_EmailFrequency' in the database.
Msg 3729, Level 16, State 1, Line 5634
Cannot DROP VIEW 'dbo.vw_DesktopModulePermissionBase' because it is being referenced by object 'vw_DesktopModulePermissions'.
Msg 2714, Level 16, State 3, Procedure vw_DesktopModulePermissionBase, Line 2 [Batch Start Line 5635]
There is already an object named 'vw_DesktopModulePermissionBase' in the database.
Msg 3729, Level 16, State 1, Line 6212
Cannot DROP VIEW 'dbo.vw_CoreMessaging_Recipients' because it is being referenced by object 'vw_MessagesForDispatch'.
Msg 2714, Level 16, State 3, Procedure vw_CoreMessaging_Recipients, Line 2 [Batch Start Line 6213]
There is already an object named 'vw_CoreMessaging_Recipients' in the database.
Msg 3729, Level 16, State 1, Line 6345
Cannot DROP VIEW 'dbo.vw_ModuleUserPermissions' because it is being referenced by object 'vw_ModulePermissions'.
Msg 3729, Level 16, State 1, Line 6349
Cannot DROP VIEW 'dbo.vw_ModuleRolePermissions' because it is being referenced by object 'vw_ModulePermissions'.
Msg 3729, Level 16, State 1, Line 6386
Cannot DROP VIEW 'dbo.vw_ModuleBase' because it is being referenced by object 'vw_TabModules'.
Msg 2714, Level 16, State 3, Procedure vw_ModuleBase, Line 3 [Batch Start Line 6387]
There is already an object named 'vw_ModuleBase' in the database.
Msg 3729, Level 16, State 1, Line 6425
Cannot DROP VIEW 'dbo.vw_ModuleTabs' because it is being referenced by object 'vw_TabModules'.
Msg 2714, Level 16, State 3, Procedure vw_ModuleTabs, Line 3 [Batch Start Line 6426]
There is already an object named 'vw_ModuleTabs' in the database.
Msg 207, Level 16, State 1, Procedure vw_Modules, Line 46 [Batch Start Line 6480]
Invalid column name 'DefinitionName'.
Msg 207, Level 16, State 1, Procedure vw_Modules, Line 58 [Batch Start Line 6480]
Invalid column name 'IsDeleted'.
Msg 207, Level 16, State 1, Procedure vw_Modules, Line 60 [Batch Start Line 6480]
Invalid column name 'IsTabDeleted'.
Msg 3729, Level 16, State 1, Line 6907
Cannot DROP VIEW 'dbo.vw_PortalBase' because it is being referenced by object 'vw_Portals'.
Msg 2714, Level 16, State 3, Procedure vw_PortalBase, Line 2 [Batch Start Line 6908]
There is already an object named 'vw_PortalBase' in the database.
Msg 3729, Level 16, State 1, Line 7005
Cannot DROP VIEW 'dbo.vw_Portals' because it is being referenced by object 'vw_PortalsDefaultLanguage'.
Msg 2714, Level 16, State 3, Procedure vw_Portals, Line 2 [Batch Start Line 7006]
There is already an object named 'vw_Portals' in the database.
Msg 3729, Level 16, State 1, Line 7372
Cannot DROP VIEW 'dbo.vw_UserRoles' because it is being referenced by object 'Journal_PermittedJournalIDs'.
Msg 2714, Level 16, State 3, Procedure vw_UserRoles, Line 2 [Batch Start Line 7373]
There is already an object named 'vw_UserRoles' in the database.
Msg 3729, Level 16, State 1, Line 7453
Cannot DROP FUNCTION 'dbo.FitsExtendedPropertyPermission' because it is being referenced by object 'UserProfileGranted'.
Msg 3729, Level 16, State 1, Line 7457
Cannot DROP VIEW 'dbo.vw_RelatedUsers' because it is being referenced by object 'FitsExtendedPropertyPermission'.
Msg 3729, Level 16, State 1, Line 7461
Cannot DROP VIEW 'dbo.vw_RelationBase' because it is being referenced by object 'vw_RelatedUsers'.
Msg 2714, Level 16, State 3, Procedure vw_RelationBase, Line 2 [Batch Start Line 7462]
There is already an object named 'vw_RelationBase' in the database.
Msg 2714, Level 16, State 3, Procedure vw_RelatedUsers, Line 2 [Batch Start Line 7484]
There is already an object named 'vw_RelatedUsers' in the database.
Msg 3729, Level 16, State 1, Line 7526
Cannot DROP VIEW 'dbo.vw_MasterPortals' because it is being referenced by object 'MasterPortalId'.
Msg 2714, Level 16, State 3, Procedure vw_MasterPortals, Line 2 [Batch Start Line 7527]
There is already an object named 'vw_MasterPortals' in the database.
Msg 3729, Level 16, State 1, Line 7540
Cannot DROP VIEW 'dbo.vw_ProfileDataTypes' because it is being referenced by object 'UserPropertyFilter'.
Msg 2714, Level 16, State 3, Procedure vw_ProfileDataTypes, Line 2 [Batch Start Line 7541]
There is already an object named 'vw_ProfileDataTypes' in the database.
Msg 3729, Level 16, State 1, Line 7554
Cannot DROP VIEW 'dbo.vw_ProfileBase' because it is being referenced by object 'UserProfileGranted'.
Msg 2714, Level 16, State 3, Procedure vw_ProfileBase, Line 3 [Batch Start Line 7555]
There is already an object named 'vw_ProfileBase' in the database.
Msg 3729, Level 16, State 1, Line 7675
Cannot DROP VIEW 'dbo.vw_JournalBase' because it is being referenced by object 'vw_JournalItems'.
Msg 2714, Level 16, State 3, Procedure vw_JournalBase, Line 2 [Batch Start Line 7676]
There is already an object named 'vw_JournalBase' in the database.
Msg 3729, Level 16, State 1, Line 7738
Cannot DROP VIEW 'dbo.vw_JournalSecurity' because it is being referenced by object 'Journal_PermittedJournalIDs'.
Msg 2714, Level 16, State 3, Procedure vw_JournalSecurity, Line 2 [Batch Start Line 7739]
There is already an object named 'vw_JournalSecurity' in the database.
Msg 3729, Level 16, State 1, Line 7956
Cannot DROP FUNCTION 'dbo.FitsExtendedPropertyPermission' because it is being referenced by object 'UserProfileGranted'.
Msg 2714, Level 16, State 3, Procedure FitsExtendedPropertyPermission, Line 4 [Batch Start Line 7957]
There is already an object named 'FitsExtendedPropertyPermission' in the database.
Msg 207, Level 16, State 1, Procedure GetAllTabsModules, Line 11 [Batch Start Line 13736]
Invalid column name 'IsTabDeleted'.

(1 row affected)

**Comment by sleupold** [comment]
if you applied TurboSchema before, you need to run TurboUnSchema first.

**Comment by andre6622** [comment]
Thank you very much. It worked now without problems.

**Comment by sleupold** [comment]
Thank you for your feedback. Have fun using DNN and TurboScripts :)
