### ISSUE TITLE
Can't upgrade to dnn 8

### ISSUE THREAD

**Issue by jakefuller1** [dnnwerk/dnnScript#9]
I ran turbo unschema first.

Trying to upgrade from 7.4.1 to 8.0.4 (and eventually to 9.3)

I get this error   /Default.aspx?tabid=842&error=Invalid+column+name+%27DefinitionName%27.%0d%0aInvalid+column+name+%27IsTabDeleted%27.&content=0

Should column name be IsDeleted not IsTabDeleted?
In table Tabs it is called IsDeleted

**Comment by sleupold** [comment]
it depends on the object, there are views using this column, when exactly do you get the error - during DNN upgrade or re-applying TurboDNN afterwards?

Please try applying latest version TurboDNN922.sql prior to the DNN upgrade.
I am still working on the upgrade script for DNN 9.3.2 and will release soon, please wait with DNN 9.3 upgrade, until it is released.

**Comment by jakefuller1** [comment]
I applied unschema, then upgrade from 7.4 to dnn 8.0.4. DNN says no error during upgrade.
Can not open site, I get this error on home page.
Apply TurboDNN922.sql prior to the DNN upgrade? I thought we had to only apply unschema?
On 7.4, do TurboDNN922.sql  first then unschema or unschema then turbo? then upgrade to 8?

**Comment by MaiklT** [comment]
Someone else seems to have the same problem here: [https://www.dnnsoftware.com/forums/forumid/107/threadid/547812/scope/posts/threadpage/1](https://www.dnnsoftware.com/forums/forumid/107/threadid/547812/scope/posts/threadpage/1)

**Comment by sleupold** [comment]
@jakefuller1 
I fear, the issue is caused by DNN updating view vw_modules during DNN 8 upgrade - isTabDeleted has been added lateron. If you are having access to the database, you may run TurboDNN922.sql in SQL Server Management Studio (after replacing the placeholders) and restart the DNN application.
Subsequently, you may apply turboSchema.sql either from SSMS or DNN SQL console.

**Comment by jakefuller1** [comment]
OK ran Turbo unschema then TurboDNN922.sql in 7.4.2 then upgraded to 8
ran TurboDNN922.sql, first 3 times had errors but 4th time lucky.
Logged into 8, checked things out, seemed OK
Decided to go for broke and upgrade to 9.2.2
Copied files over, navigate to https://yoursite.example.com/Install/UpgradeWizard.aspx to begin the upgrade.
Getting this error before upgrade (note I could and did login to DNN 8)
Compiler Error Message: BC30456: 'Email' is not a member of DotNetNuke.Entities.Users.UserMembership'.
Line 297:
Line 298:                        Case IFrameParameterType.UserEmail
Line 299:                            Return objUser.Membership.Email
Line 300:
Line 301:                        Case IFrameParameterType.UserWebsite
Source File: C:\wwwroot\test\App_Code\IFrame\Domain\IFrameParameter.vb    Line: 299 
ran TurboDNN922.sql 4 times but that did not fix problem.
Any ideas?

**Comment by sleupold** [comment]
Missy likely, you are running ah old version of iFrame module, which is incompatible with DNN 9. Please upgrade to later version from GitHub/dnmcommunity. Make sure, folder app_data/iframe is either deleted or empty afterwards.

**Comment by jakefuller1** [comment]
Getting closer? Installed IFrame 8, there was none before.
Upgraded to 9.2.2, error with skin?
https://www.dnnsoftware.com/forums/forumid/200/threadid/547930/scope/posts
[FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.UI.Skins.Skin.GetSkin(PageBase page)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by jakefuller1** [comment]
It works!
The ability to change skin/container has not worked for 7 years. Always had to do raw database edit. Not being good at sql, I just edited each cell in db for page skin and container. (copy/paste). I missed the Home page, it still had a version 7 skin and that didn't work.
Thank you for all your help. Next step, upgrade real site, rather than clone
